
import React from 'react';

const Footer: React.FC = () => {
  return (
    <footer className="text-center py-6 mt-12 border-t border-gray-700">
      <p className="text-gray-500">
        Generated by a world-class{' '}
        <a
          href="https://www.linkedin.com/in/jasonalanjames/"
          target="_blank"
          rel="noopener noreferrer"
          className="text-blue-400 hover:text-blue-300 hover:underline transition-colors"
        >
          senior frontend React engineer
        </a>
        .
      </p>
    </footer>
  );
};

export default Footer;
