
import React from 'react';

const Footer: React.FC = () => {
  return (
    <footer className="text-center py-6 mt-12 border-t border-gray-700">
      <p className="text-gray-500">
        Generated by a world-class senior frontend React engineer.
      </p>
    </footer>
  );
};

export default Footer;
